### ISSUE TITLE
Make Exasol port configurable

### ISSUE THREAD

**Issue by LOLOFF-OTTO** [abergmeier/terraform-provider-exasol#11]
It would be nice to have the Exasol port configurable in order to switch between dev and prod environment:

provider "exasol" {
  ip       = "123"
  username = "userxy"
  password = "abc"
  port = 123 <-- NEW
}

**Comment by abergmeier** [comment]
Should be done in https://github.com/abergmeier/terraform-provider-exasol/commit/23fba3049ecd7759c2959d254cf0e1229bf3dff0

**Comment by LOLOFF-OTTO** [comment]
works nicely :) Thank you!
